#!/bin/sh

# Triggers Jenkins pipeline named TestPipeline after every commits.
# - TestPipeline needs to be setup with Configure>Build Triggers>Triggers remotely>Token=mytoken
# Needs to be added under .git/hooks as post-commit.
####

curl http://localhost:8080/job/TestPipeline/build?token=mytoken
